"""The paper: template provenance, registry-backed macros, figure scripts, the draft hash, and the tectonic build.

Numbers reach the PDF only as ``\\result{entry}{stat}{digits}``, which expands to
a control sequence ``results.tex`` pre-renders for every entry, statistic and
digit count; an id the registry does not know is a LaTeX error, so the build is
the enforcement. ``\\nonresult{literal}{reason}`` is the explicit exception for
numbers from the literature.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

from . import registry as registry_mod
from .errors import DoctorError, GateError, InputError, NotFoundError, SubprocessError
from .project import Layout, now_iso, write_readme

STATS = ("mean", "std", "min", "max", "n")
DIGITS = range(0, 7)
RESULTS_HEADER = "% Generated by `research.py paper results` from experiments/registry.json. Edits here are overwritten.\n"
FIGURE_TIMEOUT_S = 600


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


# --- init ----------------------------------------------------------------------------


def init(lay: Layout, template: Path, *, main: str = "main.tex", source: str | None = None, now: str | None = None) -> dict:
    """Copy the conference template into ``paper/template/`` with a provenance record; scaffold what the author has not written yet."""
    template = Path(template)
    if not template.is_dir():
        raise NotFoundError(f"template directory {template} not found")
    if not (template / main).is_file():
        raise NotFoundError(f"--main {main!r} is not a file in {template}")
    tdir = lay.paper / "template"
    try:
        template.resolve().relative_to(lay.paper.resolve())
        raise InputError(f"--template must point at the downloaded files, not at {lay.rel(tdir)} itself")
    except ValueError:
        pass
    fresh = lay.paper / "template.new"
    if fresh.exists():
        shutil.rmtree(fresh)
    lay.paper.mkdir(parents=True, exist_ok=True)
    shutil.copytree(template, fresh, symlinks=False)
    if tdir.exists():
        shutil.rmtree(tdir)
    os.rename(fresh, tdir)
    files = {p.relative_to(tdir).as_posix(): _sha256(p) for p in sorted(tdir.rglob("*")) if p.is_file()}
    (tdir / "provenance.json").write_text(json.dumps({"source": source, "main": main, "copied_at": now or now_iso(), "files": files}, indent=1), encoding="utf-8")
    paths = [lay.rel(tdir / "provenance.json")]
    (lay.paper / "sections").mkdir(exist_ok=True)
    (lay.paper / "figures").mkdir(exist_ok=True)
    main_tex = lay.paper / "main.tex"
    if not main_tex.exists():
        text = (template / main).read_text(encoding="utf-8", errors="replace")
        if "\\input{results}" not in text:
            # the macros live in results.tex; the one edit made to the template's main is loading them
            text = text.replace("\\begin{document}", "\\input{results}\n\\begin{document}", 1)
        main_tex.write_text(text, encoding="utf-8")
        paths.append(lay.rel(main_tex))
    for dep in sorted(p for p in template.iterdir() if p.is_file() and p.suffix in (".sty", ".cls", ".bst")):
        target = lay.paper / dep.name
        if not target.exists():
            shutil.copyfile(dep, target)  # style, class and bib-style files must sit beside main.tex for tectonic to find them
            paths.append(lay.rel(target))
    if not (lay.paper / "refs.bib").exists():
        (lay.paper / "refs.bib").write_text("", encoding="utf-8")
        paths.append(lay.rel(lay.paper / "refs.bib"))
    paths.append(lay.rel(write_results(lay)))
    gi = lay.paper / ".gitignore"
    if not gi.exists():
        gi.write_text("build/\n", encoding="utf-8")
    write_readme(lay)
    return {"status": "initialised", "paths": paths}


# --- results.tex ------------------------------------------------------------------------


def _round(value: str, digits: int) -> str:
    d = Decimal(value)
    q = Decimal(1).scaleb(-digits)
    return str(d.quantize(q, rounding=ROUND_HALF_UP))


def _tex_escape(s: str) -> str:
    return s.replace("_", "\\_")


def write_results(lay: Layout) -> Path:
    """``paper/results.tex``: the macro definitions and one pre-rendered control sequence per (entry, statistic, digits)."""
    out = lay.paper / "results.tex"
    lay.paper.mkdir(parents=True, exist_ok=True)
    out.write_text(render_results(lay), encoding="utf-8")
    return out


def render_results(lay: Layout) -> str:
    reg = registry_mod.load(lay) if lay.registry_json.is_file() else {"entries": []}
    lines = [RESULTS_HEADER, "\\makeatletter"]
    lines.append("\\newcommand{\\result}[3]{\\ifcsname res@#1@#2@#3\\endcsname\\csname res@#1@#2@#3\\endcsname\\else\\errmessage{research: no registry entry '#1' with statistic '#2' at #3 digits -- run `research.py registry` and `paper results`}\\fi}")
    lines.append("\\newcommand{\\nonresult}[2]{#1}  % a literature number: #1 the literal, #2 the reason (source and locator), checked by `paper verify`")
    lines.append("\\newcommand{\\resultclass}[1]{\\ifcsname resclass@#1\\endcsname\\csname resclass@#1\\endcsname\\else\\errmessage{research: no registry entry '#1'}\\fi}")
    for e in reg.get("entries", []):
        eid = e["id"]
        lines.append(f"\\expandafter\\def\\csname resclass@{eid}\\endcsname{{{e.get('class') or 'unknown'}}}")
        stats = e.get("statistics") or {}
        for stat in STATS:
            v = stats.get(stat)
            if v is None:
                continue
            for d in DIGITS:
                rendered = str(int(v)) if stat == "n" else _round(str(v), d)
                lines.append(f"\\expandafter\\def\\csname res@{eid}@{stat}@{d}\\endcsname{{{_tex_escape(rendered)}}}")
                if stat == "n":
                    break
    lines.append("\\makeatother")
    return "\n".join(lines) + "\n"


# --- figures --------------------------------------------------------------------------------


def run_figures(lay: Layout, *, run=subprocess.run, timeout: float = FIGURE_TIMEOUT_S) -> dict:
    """Run every ``paper/figures/*.py`` with the registry path in its environment; record script, registry and output hashes."""
    figs = lay.paper / "figures"
    figs.mkdir(parents=True, exist_ok=True)
    scripts = sorted(p for p in figs.glob("*.py") if p.is_file())
    reg_path = lay.registry_json
    reg_sha = _sha256(reg_path) if reg_path.is_file() else None
    manifest = {"registry_sha256": reg_sha, "figures": {}}  # no timestamp: the draft hash covers this file
    paths = []
    scripts_dir = Path(__file__).resolve().parent.parent
    sibling = scripts_dir.parent.parent / "save-paper" / "scripts"  # research.* imports savepaper.frontmatter
    for script in scripts:
        out_pdf = figs / f"{script.stem}.pdf"
        if out_pdf.exists():
            out_pdf.unlink()
        env = dict(os.environ)
        # SOURCE_DATE_EPOCH makes matplotlib's PDF metadata reproducible, so an unchanged script + registry gives unchanged bytes
        env.update({"RESEARCH_REGISTRY": str(reg_path), "RESEARCH_FIGURE_OUT": str(out_pdf), "RESEARCH_SCRIPTS": str(scripts_dir), "RESEARCH_PROJECT_DIR": str(lay.dir), "MPLBACKEND": "pdf", "SOURCE_DATE_EPOCH": "0"})
        env["PYTHONPATH"] = os.pathsep.join([str(scripts_dir), str(sibling)] + ([env["PYTHONPATH"]] if env.get("PYTHONPATH") else []))
        try:
            proc = run(["python3", str(script)], cwd=str(figs), env=env, capture_output=True, text=True, timeout=timeout)
        except subprocess.TimeoutExpired:
            raise SubprocessError(f"figure script {script.name} timed out after {timeout}s")
        if proc.returncode != 0:
            raise SubprocessError(f"figure script {script.name} exited {proc.returncode}: {(proc.stderr or '').strip()[-400:]}", child_exit=proc.returncode)
        if not out_pdf.is_file():
            raise GateError(f"figure script {script.name} exited 0 but wrote nothing to $RESEARCH_FIGURE_OUT", findings=[{"severity": "major", "message": "no output", "location": lay.rel(script)}])
        manifest["figures"][out_pdf.name] = {"script": script.name, "script_sha256": _sha256(script), "registry_sha256": reg_sha, "output_sha256": _sha256(out_pdf)}
        paths.append(lay.rel(out_pdf))
    (figs / "manifest.json").write_text(json.dumps(manifest, indent=1), encoding="utf-8")
    paths.append(lay.rel(figs / "manifest.json"))
    return {"status": "ok", "paths": paths, "figures": len(scripts)}


# --- draft hash and build ---------------------------------------------------------------------


def draft_files(lay: Layout) -> list[Path]:
    """What the draft hash covers: every .tex/.bib/.sty/.cls/.bst under paper/ (build/ excluded), the figure scripts and PDFs, and the manifest."""
    out = []
    for p in sorted(lay.paper.rglob("*")):
        if not p.is_file() or "build" in p.relative_to(lay.paper).parts:
            continue
        rel = p.relative_to(lay.paper).as_posix()
        if p.suffix in (".tex", ".bib", ".sty", ".cls", ".bst") or p.name == "manifest.json" or (rel.startswith("figures/") and p.suffix in (".py", ".pdf")):
            out.append(p)
    return out


def draft_hash(lay: Layout) -> str:
    h = hashlib.sha256()
    for p in draft_files(lay):
        h.update(p.relative_to(lay.paper).as_posix().encode() + b"\0")
        h.update(p.read_bytes() + b"\0")
    return h.hexdigest()


def build(lay: Layout, *, final: bool = False, offline: bool = False, result_files: list[Path] | None = None, run=subprocess.run, which=shutil.which("tectonic"), timeout: float = 900) -> dict:
    """results → figures → verify → tectonic. ``--final`` additionally requires the draft review and viva bound to this draft's hash."""
    from . import verify

    if not (lay.paper / "main.tex").is_file():
        raise NotFoundError(f"no {lay.rel(lay.paper / 'main.tex')} (run `paper init` first)")
    if which is None:
        raise DoctorError("tectonic is not installed: brew install tectonic")
    figures = run_figures(lay, run=subprocess.run)
    write_results(lay)  # after the figure scripts, so nothing they wrote can stand in for the generated macros
    verified = verify.verify_paper(lay, result_files=result_files)
    dh = draft_hash(lay)
    gate = {}
    if final:
        from . import gates

        gate = gates.final_build(lay, dh)
    out_dir = lay.paper / "build"
    out_dir.mkdir(exist_ok=True)
    cmd = ["tectonic", "--keep-logs", "--keep-intermediates", "-o", str(out_dir)] + (["--only-cached"] if offline else []) + ["main.tex"]
    try:
        proc = run(cmd, cwd=str(lay.paper), capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        raise SubprocessError(f"tectonic timed out after {timeout}s")
    if proc.returncode != 0:
        log = out_dir / "main.log"
        tail = ""
        if log.is_file():
            lines = log.read_text(encoding="utf-8", errors="replace").splitlines()
            errs = [l for l in lines if l.startswith("!")]
            tail = " | ".join(errs[:5]) or " | ".join(lines[-5:])
        raise SubprocessError(f"tectonic exited {proc.returncode}: {tail or (proc.stderr or '').strip()[-400:]}", child_exit=proc.returncode, data={"log": lay.rel(log) if log.is_file() else None, "draft_hash": dh})
    pdf = out_dir / "main.pdf"
    if not pdf.is_file():
        raise SubprocessError("tectonic exited 0 but produced no main.pdf", data={"draft_hash": dh})
    write_readme(lay)
    return {"status": "built", "paths": [lay.rel(pdf)], "draft_hash": dh, "final": final, "figures": figures["figures"], "findings": verified.get("findings", []), **({"gate": gate} if gate else {})}
