"""Project root, the ``projects/<slug>/`` layout, and the generated README index."""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from savepaper.frontmatter import dump, parse

from .errors import InputError, NotFoundError

from .meta import PHASES  # noqa: E402
_SLUG = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
SUBDIRS = ("decisions", "claims", "prereg", "experiments/runs", "paper/figures", "reviews", "ideation", "viva")
README_HEADER = "# {slug}\n\n<!-- Generated by `research.py` from frontmatter and run.json. Edits here are overwritten; edit the files instead. -->\n"


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def find_root(flag: str | None) -> Path:
    """``--root`` > ``CLAUDE_PROJECT_DIR`` > cwd (the same order every command uses)."""
    if flag:
        return Path(flag)
    env = os.environ.get("CLAUDE_PROJECT_DIR")
    return Path(env) if env else Path.cwd()


def check_slug(slug: str) -> str:
    if not _SLUG.fullmatch(slug or ""):
        raise InputError(f"slug {slug!r} must be lowercase kebab-case (a-z, 0-9, single hyphens)")
    return slug


@dataclass(frozen=True)
class Layout:
    root: Path
    slug: str

    @classmethod
    def open(cls, root: Path, slug: str) -> "Layout":
        lay = cls(Path(root), check_slug(slug))
        if not lay.project_md.exists():
            raise NotFoundError(f"no project at {lay.dir} (run `init {slug}` first)")
        return lay

    @property
    def dir(self) -> Path:
        return self.root / "projects" / self.slug

    @property
    def project_md(self) -> Path:
        return self.dir / "project.md"

    @property
    def readme(self) -> Path:
        return self.dir / "README.md"

    @property
    def literature_md(self) -> Path:
        return self.dir / "literature.md"

    @property
    def decisions(self) -> Path:
        return self.dir / "decisions"

    @property
    def claims(self) -> Path:
        return self.dir / "claims"

    @property
    def prereg(self) -> Path:
        return self.dir / "prereg"

    @property
    def runs(self) -> Path:
        return self.dir / "experiments" / "runs"

    @property
    def registry_json(self) -> Path:
        return self.dir / "experiments" / "registry.json"

    @property
    def paper(self) -> Path:
        return self.dir / "paper"

    @property
    def reviews(self) -> Path:
        return self.dir / "reviews"

    @property
    def ideation(self) -> Path:
        return self.dir / "ideation"

    @property
    def viva(self) -> Path:
        return self.dir / "viva"

    @property
    def papers_sources(self) -> Path:
        return self.root / "papers" / "sources"

    def rel(self, path: Path) -> str:
        return path.relative_to(self.root).as_posix()

    def read_project(self) -> tuple[dict, str]:
        return parse(self.project_md.read_text(encoding="utf-8"))

    def write_project(self, fm: dict, body: str) -> None:
        self.project_md.write_text(dump(fm, body), encoding="utf-8")


def init_project(root: Path, slug: str, *, question: str = "", now: str | None = None) -> Layout:
    """Create the contract tree; an existing project is left exactly as it is."""
    lay = Layout(Path(root), check_slug(slug))
    for rel in SUBDIRS:
        (lay.dir / rel).mkdir(parents=True, exist_ok=True)
    if not lay.project_md.exists():
        fm = {
            "type": "Research Project",
            "title": slug,
            "description": question,
            "question": question,
            "phase": PHASES[0],
            "venue": None,
            "submission_ready": False,
            "created": now or now_iso(),
        }
        lay.write_project(fm, "")
    if not lay.literature_md.exists():
        fm = {"type": "Literature", "title": f"{slug} literature", "entries": [], "search_log": []}
        lay.literature_md.write_text(dump(fm, "Entries link `papers/sources/<id>.md`; a non-arXiv entry carries `verified: {by: human:seongjin, at}`. `search_log` records what was searched where, so \"not found within this search\" is never read as \"no prior work\".\n"), encoding="utf-8")
    write_readme(lay)
    return lay


def frontmatter_files(lay: Layout) -> list[Path]:
    out = []
    for path in sorted(lay.dir.rglob("*.md")):
        if path.name == "README.md" or "template" in path.parts or "build" in path.parts:
            continue
        out.append(path)
    return out


def write_readme(lay: Layout) -> Path:
    """Regenerate ``README.md`` from every frontmatter file and every ``run.json`` under the project."""
    groups: dict[str, list[str]] = {}
    for path in frontmatter_files(lay):
        fm, _ = parse(path.read_text(encoding="utf-8"))
        if not fm.get("type"):
            continue
        rel = path.relative_to(lay.dir).as_posix()
        title = fm.get("title") or path.stem
        extra = [str(fm[k]) for k in ("kind", "claim_status", "phase", "scope", "lane", "chosen", "decided_by") if fm.get(k) not in (None, "")]
        if fm.get("type") == "Decision" and fm.get("chosen") is None:
            extra.append("open")
        meta = f" ({'; '.join(extra)})" if extra else ""
        desc = str(fm.get("description") or "").strip().splitlines()[0] if fm.get("description") else ""
        groups.setdefault(str(fm["type"]), []).append(f"* [{title}]({rel}){meta}" + (f" - {desc}" if desc else ""))
    lines = [README_HEADER.format(slug=lay.slug)]
    for typ in sorted(groups):
        lines.append(f"\n## {typ}\n\n" + "\n".join(groups[typ]) + "\n")
    runs = sorted(p for p in lay.runs.glob("*/run.json")) if lay.runs.exists() else []
    if runs:
        lines.append("\n## Runs\n\n")
        for rj in runs:
            try:
                r = json.loads(rj.read_text(encoding="utf-8"))
            except ValueError:
                r = {}
            sealed = " sealed" if (rj.parent / "seal.json").exists() else ""
            lines.append(f"* {rj.parent.name}: {r.get('name', '')} ({r.get('status', '?')}; {r.get('class', '?')}{sealed})\n")
    lay.readme.write_text("".join(lines), encoding="utf-8")
    return lay.readme
