"""``papers/README.md``: an OKF-style index regenerated from frontmatter. Never hand-edited."""

from __future__ import annotations

import re
from pathlib import Path

from .frontmatter import parse

HEADER = "# Index of Papers\n\n<!-- Generated by `save_paper.py index` from frontmatter. Edits here are overwritten; edit the papers instead. -->\n"


def _first_sentence(text: str, limit: int = 220) -> str:
    text = re.sub(r"\s+", " ", text or "").strip()
    m = re.match(r"(.{20,}?[.!?])(\s|$)", text)
    s = m.group(1) if m else text
    return s if len(s) <= limit else s[: limit - 1].rstrip() + "…"


def _trust(fm: dict) -> str:
    v = fm.get("verified")
    if not v:
        return "unverified"
    entries = v if isinstance(v, list) else [v]
    return "human-reviewed" if any(str(e.get("by", "")).startswith("human:") for e in entries) else "machine-confirmed"


def _entries(md_files: list[Path], papers_dir: Path) -> list[tuple[str, str]]:
    rows = []
    for path in md_files:
        fm, _ = parse(path.read_text(encoding="utf-8"))
        if not fm.get("type"):
            continue
        rel = path.relative_to(papers_dir).as_posix()
        title = fm.get("title") or path.stem
        desc = _first_sentence(fm.get("description", ""))
        extra = []
        arx = fm.get("arxiv") or {}
        if arx.get("id"):
            extra.append(f"arXiv:{arx['id']}v{arx.get('version', '')}")
        if arx.get("published"):
            extra.append(str(arx["published"]))
        extra.append(_trust(fm))
        route = (fm.get("conversion") or {}).get("route")
        if route and route != "html":
            extra.append(f"route:{route}")
        if fm.get("status"):
            extra.append(str(fm["status"]))
        meta = f" ({'; '.join(extra)})" if extra else ""
        sort_key = str(arx.get("published") or "") + title
        rows.append((sort_key, f"* [{title}]({rel}){meta} - {desc}" if desc else f"* [{title}]({rel}){meta}"))
    rows.sort(key=lambda r: r[0], reverse=True)
    return rows


def build_index(papers_dir: Path) -> str:
    notes = sorted(p for p in papers_dir.glob("*.md") if p.name != "README.md")
    sources = sorted((papers_dir / "sources").glob("*.md")) if (papers_dir / "sources").exists() else []
    out = [HEADER]
    out.append("\n# Notes\n\n")
    note_rows = _entries(notes, papers_dir)
    out.append("\n".join(r for _, r in note_rows) + "\n" if note_rows else "_No notes yet._\n")
    out.append("\n# Sources\n\n")
    src_rows = _entries(sources, papers_dir)
    out.append("\n".join(r for _, r in src_rows) + "\n" if src_rows else "_No sources yet._\n")
    return "".join(out)


def write_index(papers_dir: Path) -> Path:
    target = papers_dir / "README.md"
    target.write_text(build_index(papers_dir), encoding="utf-8")
    return target
