"""Seam: ``project.init_project`` / ``project.Layout`` / ``project.write_readme`` on a ``tmp_path`` root with an injected clock."""

from pathlib import Path

import pytest

from research import project
from research.errors import InputError, NotFoundError
from savepaper.frontmatter import parse

NOW = "2026-09-07T01:02:03Z"


def test_init_creates_the_contract_tree_and_is_idempotent(tmp_path):
    lay = project.init_project(tmp_path, "toy-ablation", question="Does X beat Y?", now=NOW)
    assert lay.dir == tmp_path / "projects" / "toy-ablation"
    for rel in ("decisions", "claims", "prereg", "experiments/runs", "paper/figures", "reviews", "ideation", "viva"):
        assert (lay.dir / rel).is_dir(), rel
    fm, _ = parse(lay.project_md.read_text())
    assert fm["type"] == "Research Project" and fm["question"] == "Does X beat Y?"
    assert fm["phase"] == "exploring" and fm["submission_ready"] is False and fm["created"] == NOW
    lit, _ = parse(lay.literature_md.read_text())
    assert lit["type"] == "Literature"
    assert "Generated by" in lay.readme.read_text()
    (lay.dir / "claims" / "keep.txt").write_text("x")
    again = project.init_project(tmp_path, "toy-ablation", question="ignored", now="2027-01-01T00:00:00Z")
    fm2, _ = parse(again.project_md.read_text())
    assert fm2["question"] == "Does X beat Y?" and fm2["created"] == NOW, "a second init is a no-op"
    assert (lay.dir / "claims" / "keep.txt").exists()


@pytest.mark.parametrize("bad", ["Toy", "toy_ablation", "toy ablation", "", "-toy", "toy--x"])
def test_slug_must_be_lowercase_kebab(tmp_path, bad):
    with pytest.raises(InputError) as exc:
        project.init_project(tmp_path, bad, question="q", now=NOW)
    assert "slug" in str(exc.value)


def test_layout_of_a_missing_project_is_exit_3(tmp_path):
    with pytest.raises(NotFoundError):
        project.Layout.open(tmp_path, "nope")


def test_readme_indexes_frontmatter_files_and_runs(tmp_path):
    lay = project.init_project(tmp_path, "toy", question="q", now=NOW)
    (lay.dir / "claims" / "C01.md").write_text("---\ntype: Claim\ntitle: X beats Y\nkind: hypothesis\nby: human:seongjin\nclaim_status: candidate\n---\n\nbody\n")
    run = lay.dir / "experiments" / "runs" / "r001"
    run.mkdir(parents=True)
    (run / "run.json").write_text('{"name": "pilot", "status": "completed", "class": "exploratory"}')
    project.write_readme(lay)
    text = lay.readme.read_text()
    assert "[X beats Y](claims/C01.md)" in text and "hypothesis" in text and "candidate" in text
    assert "r001" in text and "pilot" in text and "completed" in text
    assert "# Generated" in text or "Generated by" in text


def test_find_root_prefers_flag_then_env_then_cwd(tmp_path, monkeypatch):
    monkeypatch.setenv("CLAUDE_PROJECT_DIR", str(tmp_path / "env"))
    assert project.find_root("/x/flag") == Path("/x/flag")
    assert project.find_root(None) == tmp_path / "env"
    monkeypatch.setenv("CLAUDE_PROJECT_DIR", "")
    monkeypatch.chdir(tmp_path)
    assert project.find_root(None) == tmp_path
