"""Seam: ``paper.init`` / ``paper.write_results`` / ``paper.run_figures`` / ``paper.build`` with tectonic behind a ``run=`` seam; figure scripts are real subprocesses."""

import json
import subprocess
import sys
from pathlib import Path

import pytest

from research import paper, project, registry, runs
from research.errors import GateError, NotFoundError, SubprocessError

FAKE = Path(__file__).with_name("fixtures") / "fake_experiment.py"
TEMPLATE = Path(__file__).with_name("fixtures") / "template"
NOW = "2026-09-07T01:00:00Z"


@pytest.fixture
def lay(tmp_path):
    lay = project.init_project(tmp_path, "toy", question="q", now=NOW)
    runs.start(lay, "pilot", [sys.executable, str(FAKE)], seeds=[1, 2, 3], now=NOW)
    registry.rebuild(lay)
    return lay


def test_init_copies_template_records_provenance_and_scaffolds(lay):
    out = paper.init(lay, TEMPLATE, main="main.tex", source="https://example.org/toyconf-2026.zip", now=NOW)
    prov = json.loads((lay.paper / "template" / "provenance.json").read_text())
    assert prov["source"] == "https://example.org/toyconf-2026.zip" and set(prov["files"]) == {"main.tex", "toyconf.sty"} and prov["copied_at"] == NOW
    assert (lay.paper / "main.tex").read_text() == (TEMPLATE / "main.tex").read_text()
    assert (lay.paper / "refs.bib").exists() and (lay.paper / "sections").is_dir() and (lay.paper / "results.tex").exists()
    assert "projects/toy/paper/results.tex" in out["paths"]
    (lay.paper / "main.tex").write_text("edited")
    paper.init(lay, TEMPLATE, main="main.tex", now=NOW)
    assert (lay.paper / "main.tex").read_text() == "edited", "a second init keeps the author's main.tex"
    with pytest.raises(NotFoundError):
        paper.init(lay, TEMPLATE, main="nope.tex", now=NOW)


def test_results_tex_defines_rounded_macros_from_the_registry(lay):
    paper.init(lay, TEMPLATE, main="main.tex", now=NOW)
    text = paper.write_results(lay).read_text()
    assert r"\newcommand{\result}[3]" in text and r"\newcommand{\nonresult}[2]" in text
    assert r"\csname res@r001/baseline/accuracy@mean@2\endcsname" in text and "{0.71}" in text
    assert "res@r001/baseline/accuracy@mean@4" in text and "{0.7100}" in text
    assert "res@r001/baseline/accuracy@n@0" in text and "{3}" in text
    assert "res@r001/method/accuracy@std@3" in text
    assert "PackageError" in text or "errmessage" in text, "an unknown id fails the LaTeX build, not silently"
    assert "Generated by" in text


def test_figures_run_scripts_against_the_registry_and_write_a_manifest(lay):
    paper.init(lay, TEMPLATE, main="main.tex", now=NOW)
    script = lay.paper / "figures" / "acc.py"
    script.write_text(
        "import json, os, sys\n"
        "reg = json.load(open(os.environ['RESEARCH_REGISTRY']))\n"
        "assert reg['entries'][0]['id'] == 'r001/baseline/accuracy'\n"
        "sys.path.insert(0, os.environ['RESEARCH_SCRIPTS'])\n"
        "from research.registry import load\n"
        "assert load(os.environ['RESEARCH_REGISTRY'])['entries']\n"
        "open(os.environ['RESEARCH_FIGURE_OUT'], 'wb').write(b'%PDF-1.4 fake')\n"
    )
    out = paper.run_figures(lay)
    man = json.loads((lay.paper / "figures" / "manifest.json").read_text())
    assert set(man["figures"]) == {"acc.pdf"} and man["figures"]["acc.pdf"]["script"] == "acc.py"
    assert len(man["figures"]["acc.pdf"]["script_sha256"]) == 64 and man["registry_sha256"] == man["figures"]["acc.pdf"]["registry_sha256"]
    assert (lay.paper / "figures" / "acc.pdf").read_bytes().startswith(b"%PDF")
    assert "projects/toy/paper/figures/acc.pdf" in out["paths"]
    script.write_text("raise SystemExit(4)")
    with pytest.raises(SubprocessError) as exc:
        paper.run_figures(lay)
    assert exc.value.child_exit == 4
    script.write_text("pass")
    with pytest.raises(GateError):
        paper.run_figures(lay)  # script exited 0 but produced no file


def test_draft_hash_covers_tex_bib_and_manifest_only(lay):
    paper.init(lay, TEMPLATE, main="main.tex", now=NOW)
    h1 = paper.draft_hash(lay)
    (lay.paper / "build").mkdir(exist_ok=True)
    (lay.paper / "build" / "main.log").write_text("log")
    assert paper.draft_hash(lay) == h1
    (lay.paper / "sections" / "intro.tex").write_text("new")
    h2 = paper.draft_hash(lay)
    assert h2 != h1 and len(h2) == 64


def tectonic_fake(ok=True):
    def run(cmd, **kw):
        assert cmd[0] == "tectonic" and "--keep-logs" in cmd and "-o" in cmd
        out = Path(cmd[cmd.index("-o") + 1])
        if ok:
            (out / "main.pdf").write_bytes(b"%PDF")
            return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")
        (out / "main.log").write_text("! Undefined control sequence.\nl.12 \\reslt")
        return subprocess.CompletedProcess(cmd, 1, stdout="", stderr="error: something bad")

    return run


def test_build_runs_results_figures_verify_then_tectonic(lay, monkeypatch):
    paper.init(lay, TEMPLATE, main="main.tex", now=NOW)
    (lay.paper / "sections" / "intro.tex").write_text("Intro.\n")
    (lay.paper / "sections" / "results.tex").write_text(r"Accuracy is \result{r001/method/accuracy}{mean}{2} (\result{r001/method/accuracy}{n}{0} seeds)." + "\n")
    out = paper.build(lay, run=tectonic_fake(), which="tectonic")
    assert out["status"] == "built" and out["paths"][0].endswith("build/main.pdf")
    (lay.paper / "sections" / "results.tex").write_text("Accuracy is 0.81.\n")
    with pytest.raises(GateError) as exc:
        paper.build(lay, run=tectonic_fake(), which="tectonic")
    assert exc.value.findings[0]["location"].startswith("projects/toy/paper/sections/results.tex:1")
    (lay.paper / "sections" / "results.tex").write_text(r"Accuracy is \result{r001/method/accuracy}{mean}{2}." + "\n")
    with pytest.raises(SubprocessError) as exc:
        paper.build(lay, run=tectonic_fake(ok=False), which="tectonic")
    assert exc.value.child_exit == 1 and "Undefined control sequence" in str(exc.value)


def test_final_build_is_gated_on_review_and_viva(lay):
    paper.init(lay, TEMPLATE, main="main.tex", now=NOW)
    (lay.paper / "sections" / "intro.tex").write_text("Intro.\n")
    (lay.paper / "sections" / "results.tex").write_text("Nothing.\n")
    with pytest.raises(GateError) as exc:
        paper.build(lay, run=tectonic_fake(), which="tectonic", final=True)
    msgs = " ".join(f["message"] for f in exc.value.findings)
    assert "draft review" in msgs and "viva" in msgs


def test_build_needs_tectonic(lay):
    paper.init(lay, TEMPLATE, main="main.tex", now=NOW)
    (lay.paper / "sections" / "intro.tex").write_text("")
    (lay.paper / "sections" / "results.tex").write_text("")
    from research.errors import DoctorError

    with pytest.raises(DoctorError):
        paper.build(lay, which=None)


def test_draft_hash_is_stable_across_builds_and_covers_figures(lay):
    paper.init(lay, TEMPLATE, main="main.tex", now=NOW)
    (lay.paper / "sections" / "intro.tex").write_text("Intro.\n")
    (lay.paper / "sections" / "results.tex").write_text("Nothing.\n")
    (lay.paper / "figures" / "acc.py").write_text(
        "import os, matplotlib\nmatplotlib.use('pdf')\nimport matplotlib.pyplot as plt\nfig, ax = plt.subplots()\nax.plot([1, 2])\nfig.savefig(os.environ['RESEARCH_FIGURE_OUT'])\n"
    )
    h1 = paper.build(lay, run=tectonic_fake(), which="tectonic")["draft_hash"]
    h2 = paper.build(lay, run=tectonic_fake(), which="tectonic")["draft_hash"]
    assert h1 == h2, "an unchanged draft keeps its hash, or every build would invalidate the review"
    (lay.paper / "figures" / "acc.py").write_text("import os\nopen(os.environ['RESEARCH_FIGURE_OUT'], 'wb').write(b'%PDF other')\n")
    assert paper.build(lay, run=tectonic_fake(), which="tectonic")["draft_hash"] != h1
    assert "generated_at" not in json.loads((lay.paper / "figures" / "manifest.json").read_text())


def test_figure_scripts_cannot_replace_results_tex(lay):
    paper.init(lay, TEMPLATE, main="main.tex", now=NOW)
    (lay.paper / "sections" / "intro.tex").write_text("")
    (lay.paper / "sections" / "results.tex").write_text("")
    (lay.paper / "figures" / "evil.py").write_text(
        "import os\nopen(os.path.join(os.environ['RESEARCH_PROJECT_DIR'], 'paper', 'results.tex'), 'w').write('\\\\newcommand{\\\\result}[3]{0.99}')\n"
        "open(os.environ['RESEARCH_FIGURE_OUT'], 'wb').write(b'%PDF')\n"
    )
    paper.build(lay, run=tectonic_fake(), which="tectonic")
    assert "0.99" not in (lay.paper / "results.tex").read_text()


def test_init_copies_cls_and_bst_and_refuses_overlap(lay, tmp_path):
    tpl = tmp_path / "tpl"
    tpl.mkdir()
    (tpl / "main.tex").write_text("\\documentclass{conf}\\begin{document}x\\end{document}")
    (tpl / "conf.cls").write_text("cls")
    (tpl / "conf.bst").write_text("bst")
    paper.init(lay, tpl, main="main.tex", now=NOW)
    assert (lay.paper / "conf.cls").exists() and (lay.paper / "conf.bst").exists()
    (lay.paper / "template" / "conf.cls").write_text("edited")
    with pytest.raises(__import__("research.errors", fromlist=["InputError"]).InputError):
        paper.init(lay, lay.paper / "template", main="main.tex", now=NOW)
    assert (lay.paper / "template" / "conf.cls").read_text() == "edited"
